# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
  # app service for your backend
  app:
    container_name: nest-js
    env_file:
      - '.env'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    
    depends_on:
      - database
  pgadmin:
    image: dpage/pgadmin4 
    restart: always 
    container_name: nest-pgadmin4 
    ports: 
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    depends_on: 
        - database
    

volumes:
  pgdata:

  # # start the mongodb service as container
  # database:
  #   image: mongo:6.0
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: # DATABASE_NAME
  #     MONGO_INITDB_ROOT_PASSWORD: # DATABASE_USER